name: "Comment run"
on:
  issue_comment:
    types: [created, edited]

jobs:
  comment-run:
    runs-on: ubuntu-20.04
    steps:
    - name: Install emojis
      run: sudo apt install fonts-noto-color-emoji
    - name: Update NPM
      run: npm install -g npm@latest
    - uses: actions/checkout@v2
      with:
        # 0 indicates all history
        fetch-depth: 0
    - uses: nwtgck/actions-comment-run@v1.1.3
      with:
        github-token: ${{ secrets.CUSTOM_GH_TOKEN }}
        allowed-associations: '["OWNER", "MEMBER"]'
      env:
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}
